---
- name: Converge
  hosts: all

  pre_tasks:

    - name: Include scenario specific variables
      include_vars: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/vars.yml"

    - name: Install python, pip and virtualenv
      apt:
        name:
          - python-dev
          - python-pip
          - python-virtualenv

    - name: Create virtuelenv for large_image
      command: virtualenv "{{ large_image_virtualenv }}"
      args:
        creates: "{{ large_image_virtualenv }}"

    - name: Install pytest to run the tests
      pip:
        name: pytest
        virtualenv: "{{ large_image_virtualenv }}"
      when: not large_image_include_vips

    - name: Copy test file to the container
      copy:
        src: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/tests/request_tile_in_container.py"
        dest: "request_tile_in_container.py"
      when: not large_image_include_vips

  tasks:
    - include_role:
        name: large_image
